CREATE TABLE IF NOT EXISTS PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT DEFAULT NOT NULL,
    START_DATE TIMESTAMP DEFAULT NOT NULL,
    END_DATE TIMESTAMP DEFAULT NOT NULL,
    PRICE_LIST INT DEFAULT NOT NULL,
    PRODUCT_ID INT DEFAULT NOT NULL,
    PRIORITY INT DEFAULT NOT NULL,
    PRICE DOUBLE DEFAULT NOT NULL,
    CURR VARCHAR(3) DEFAULT NOT NULL);

